import sys
import os
import yaml

source_dir = os.path.dirname(os.path.abspath(__file__))
materials_dir = sys.argv[1]
target_dir = sys.argv[2]

os.makedirs(target_dir, exist_ok=True)

f = open(f"{target_dir}/fields.hpp.in", "w", encoding="utf-8")
f.write("// AUTO-GENERATED BY opt_fields_gen.py\n\n")

f2 = open(f"{target_dir}/fields.cpp.in", "w", encoding="utf-8")
f2.write("// AUTO-GENERATED BY opt_fields_gen.py\n\n")


def item_iterator(file):
    data = yaml.safe_load(open(os.path.join(materials_dir, "data", file), "r", encoding="utf-8"))
    for row in data:
        if row.get("deprecated", False):
            continue

        yield row


def gen_fields_enum(enum, file, parent, name_field="name", key_field="key"):
    max_key = 0

    f.write(f"enum class {enum} : {parent} {{\n")

    item_names = dict()

    for row in item_iterator(file):
        key = row[key_field]
        name = row[name_field]
        max_key = max(key, max_key)
        item_names[key] = name

        f.write(f"  {name} = {key},\n")

    f.write("};\n")

    f.write("\n")
    f.write("template<>\n")
    f.write(
        f"constexpr inline size_t enum_capacity<{enum}>() {{ return {max_key + 1}; }}\n"
    )
    f.write(
        f"extern constinit const std::array<const char*, enum_capacity<{enum}>()> {enum}_names;\n"
    )
    f.write("\n")
    f.write("/// Safe way to get item name from an enum value.\n")
    f.write(
        "/// Some values might not have a name defined, this function has checks for that.\n"
    )
    f.write(f"inline std::string_view enum_item_name({enum} val) {{\n")
    f.write(f" if (std::to_underlying(val) >= enum_capacity<{enum}>()) {{\n")
    f.write("    return std::string_view{};\n")
    f.write("  }\n")
    f.write(f"  const char *str = {enum}_names[std::to_underlying(val)];\n")
    f.write("  return str ? std::string_view{ str } : std::string_view {};\n")
    f.write("}\n")

    f.write("\n")

    f2.write(
        f"constinit const std::array<const char*, enum_capacity<{enum}>()> {enum}_names {{\n"
    )
    for i in range(max_key + 1):
        f2.write("  ")
        if name := item_names.get(i):
            f2.write(f'"{name}"')
        else:
            f2.write("nullptr")

        f2.write(",\n")
    f2.write("};\n\n")


enum_types = {
    "material_class": "MaterialClass",
    "material_type": "MaterialType",
    "write_protection": "WriteProtection",
    "tags": "MaterialTag",
    "certifications": "MaterialCertification",
}


def gen_fields_data(field_enum, file):
    gen_fields_enum(field_enum, file, "Field")

    for row in item_iterator(file):
        f.write("template<>\n")
        f.write(f"struct FieldTraits<{field_enum}::{row['name']}> {{\n")

        type = row["type"]
        type_str = type
        # Append _ suffix for C++ keywords
        if type == "int" or type == "enum":
            type_str += "_"

        f.write(
            f"  static constexpr FieldType field_type = FieldType::{type_str};\n"
        )

        if v := row.get("max_length"):
            f.write(f"  static constexpr PayloadPos max_length = {v};\n")

        match type:
            case "string":
                f.write(
                    f"  using Buffer = std::array<char, {row['max_length']}>;\n"
                )
                if v := row.get("example"):
                    f.write(
                        f'  static constexpr const char *example = "{v}";\n')

            case "number" | "int":
                if v := row.get("example"):
                    f.write(f"  static constexpr const auto example = {v};\n")

            case "enum":
                enum_type = enum_types[row["name"]]

                if v := row.get("example"):
                    f.write(
                        f"  static constexpr const auto example = {enum_type}::{v};\n"
                    )

                f.write(f"  using Enum = {enum_type};\n")

            case "enum_array":
                enum_type = enum_types[row["name"]]

                f.write(f"  using Enum = {enum_type};\n")
                f.write(
                    f"  using Buffer = std::array<{enum_type}, {row['max_length']}>;\n"
                )

            case _:
                pass

        f.write("};\n\n")


gen_fields_enum("MaterialClass", "material_class_enum.yaml", "uint8_t")
gen_fields_enum("WriteProtection", "write_protection_enum.yaml", "uint8_t")
gen_fields_enum("MaterialType",
                "material_type_enum.yaml",
                "uint16_t",
                name_field="abbreviation")

gen_fields_enum("MaterialTag", "tags_enum.yaml", "uint16_t")
gen_fields_enum("MaterialCertification", "material_certifications_enum.yaml",
                "uint16_t")

# Enums must be before field definitions, because field meta is referencing them
gen_fields_data("MainField", "main_fields.yaml")
gen_fields_data("AuxField", "aux_fields.yaml")
